<h3>Information</h3>
<ul id="loan_account_tabs" class="tabs">
	<li>
		<a href="#" id="loan_account_tab_view" class="tab-item-link ">
			<span>Account Information</span>
		</a>
	</li>
	<li>
		<a href="#" id="loans_tab_view" class="tab-item-link ">
			<span>Loans</span>
		</a>
	</li>

</ul>

<script>
	var loan_account_tab = 	new varienTabs('loan_account_tabs','tab_container','loan_account_tab_view',[]);
</script>