<div ng-app="manage-loan">
	<div ng-controller="loan-controller">
		<table>
			<thead>
				<tr>
					<th>Loan ID</th>
					<th>First Name</th>
					<th>Last Name</th>
					<th>Loan value</th>
					<th>Status</th>
					<th>Action</th>
				</tr>
			</thead>

			<tbody>
				<tr ng-repeat="loan in loans">
					<td>{{loan.loan_id}}</td>
					<td>{{loan.first_name}}</td>
					<td>{{loan.last_name}}</td>
					<td>{{loan.loan_value}}</td>
					<td>{{loan.status}}</td>
					<td></td>
				</tr>

			</tbody>
		</table>
	</div>
</div>


<script>

	var app = angular.module('manage-loan',[]);

	app.controller('loan-controller',function($scope){
		$scope.loans  = [{
			loan_id:1,
			first_name:'cj',
			last_name: 'labs'
		}];
	});

</script>